import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="http://localhost:3000/games/Gugudan" className={styles.card}>
            <h2>구구단 &rarr;</h2>
            <p>구구단 게임 입니다. react-hook-form과 yup validation을 추가한</p>
          </a>

          <a
            href="http://localhost:3000/games/Gugudan2"
            className={styles.card}
          >
            <h2>구구단2 &rarr;</h2>
            <p>
              구구단 게임 입니다. react-hook-form은 추가됬지만 input에 숫자만
              입력 가능합니다.
            </p>
          </a>

          <a
            href="http://localhost:3000/games/WordRelay"
            className={styles.card}
          >
            <h2>끝말잇기 &rarr;</h2>
            <p>끝말잇기 게임입니다. 알파벳이 입력된다면 에러를 뱉을겁니다.</p>
          </a>

          <a
            href="http://localhost:3000/games/WordRelay2"
            className={styles.card}
          >
            <h2>끝말잇기2 &rarr;</h2>
            <p>
              두 번째 끝말잇기입니다. 숫자는 인풋값에 입력을 할 수
              없습니다.(미완성)
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
